### ISSUE TITLE
Built and tested?

### ISSUE THREAD

**Issue by jamislike** [newAM/poe-addon#20]
I notice in the current readme you say "Proceed with caution, I have not made this yet due to part shortages."

Did you ever build and test it to confirm the circuit works?
Thanks!

**Comment by newAM** [comment]
I did build three with everything but the microchip EEPROM which was still out of stock.

I've been using one for over two years as hub for my DIY long range temperature sensors (not on GitHub, still need to clean this up 😅).

I'll update the readme and add some photos when I'm at my desktop later today!
